# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69a1bfb0986c51bf362288790a422bde96aa5faed267a022b838ef13fcf48241a42a910b7a0952335d1bf93fa41e51357b67827bc521e0570a75cb55ddaec80f

test:
  secret_key_base: a8a2c2d76baafacaccb4bc261713bf06ee56cb27af40c4d4f99b751fe4d1ba0c40ba71565e1d5fd67a77cc8936192d9b18f0e5979a774d1e8cc4405255db7505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
