# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Tag.destroy_all

tag_array = ["Romantic Era", "Poetry", "Victorian Era", "Ancient Greek", "Latin", "Classical", "Epic", "Fiction", "Mortality", "Redemption", "" "Ulysses", "James Joyce", "Herman Melville", "Moby Dick", "Don Quixote", "Miguel de Cervantes", "Hamlet", "Macbeth", "Othello", "William Shakespeare", "War and Peace", "Leo Tolstoy", "Crime and Punishment", "Fyodor Dostoevsky", "The Iliad", "The Odyssey", "Homer", "The Aeneid", "Virgil", "The Georgics", "The Eclogues", "Metamorphoses", "Ovid", "Catullus", "The Great Gatsby", "F. Scott Fitzgerald", "Paradise Lost", "John Milton", "Inferno", "Dante Alighieri", "The Brothers Karamzov", "Madame Bovary", "Gustave Flaubert", "The Decline and Fall of the Roman Empire", "Edward Gibbon", "Slaughterhouse 5", "Cat's Cradle", "Kurt Vonnegut", "The Sound and the Fury", "William Faulkner", "Jane Eyre", "Charlotte Bronte", "Heart of Darkenss", "Joseph Conrad", "Franz Kafa", "Companionship as salvation", "Convention and rebellion", "Dangers of ignorance", "Darkness and light", "Death – inevitable or tragedy", "Desire to escape", "Destruction of beauty", "Disillusionment and dreams", "Displacement", "Empowerment", "Emptiness of attaining false dream", "Everlasting love", "Evils of racism", "Facing darkness", "Facing reality", "Fading beauty", "Faith versus doubt", "Family – blessing or curse", "Fate and free will", "Fear of failure", "Female roles", "Fulfillment", "Good versus bad", "Greed as downfall", "Growing up – pain or pleasure", "Hazards of passing judgment", "Heartbreak of betrayal", "Heroism – real and perceived", "Hierarchy in nature", "Identity crisis", "Illusion of power", "Immortality", "Individual versus society", "Inner versus outer strength", "Injustice", "Isolation", "Isolationism - hazards", "Knowledge versus ignorance", "Loneliness as destructive force", "Losing hope", "Loss of innocence", "Lost honor", "Lost love", "Love and sacrifice", "Man against nature", "Manipulation", "Materialism as downfall", "Motherhood", "Names – power and significance", "Nationalism – complications", "Nature as beauty", "Necessity of work", "Oppression of women", "Optimism – power or folly", "Overcoming – fear, weakness, vice", "Patriotism – positive side or complications", "Power and corruption", "Power of silence", "Power of tradition", "Power of wealth", "Power of words", "Pride and downfall", "Progress – real or illusion", "Quest for discovery", "Quest for power", "Rebirth", "Reunion", "Role of men", "Role of Religion – virtue or hypocrisy", "Role of women", "Self – inner and outer", "Self-awareness", "Self-preservation", "Self-reliance", "Social mobility", "Technology in society – good or bad", "Temporary nature of physical beauty", "Temptation and destruction", "Totalitarianism", "Vanity as downfall", "Vulnerability of the meek", "Vulnerability of the strong", "War – glory, necessity, pain, tragedy", "Will to survive", "Wisdom of experience", "Working class struggles", "Youth and beauty"]

tag_array.each do |tag|
  Tag.create({
    name: tag  
  })
end